POST http://localhost:3333/student/register
Content-Type: application/json

{
    "name": "Edu",
    "email": "edu@gmail.com",
    "password": "12345",
    "classroom": "202"
}

###

POST http://localhost:3333/student/login
Content-Type: application/json

{
    "email": "iury@gmail.com",
    "password": "12345"
}

###

POST http://localhost:3333/teacher/register
Content-Type: application/json

{
    "name": "Professor",
    "email": "professor@gmail.com",
    "password": "12345"
}

###

POST http://localhost:3333/teacher/login
Content-Type: application/json

{
    "email": "professor@gmail.com",
    "password": "12345"
}

###

GET http://localhost:3333/student/2/available-exams

###

GET http://localhost:3333/student/exams/7

###

POST http://localhost:3333/student/exam-responses
Content-Type: application/json

{
    "studentId": 1,
    "examId": 1,
    "classroomId": 8,
    "responses": {

    }
}

###

GET http://localhost:3333/teacher/exams

###

POST http://localhost:3333/teacher/exams
Content-Type: application/json

{
    "title": "Prova de Serviços Juridicos",
    "classroomName": "202",
    "description": "Provinha de de base tecnica",
    "applicationDate": "31/05/2024",
    "questions": [
    {
      "question": "Qual é a capital do Brasil?",
      "options": {
        "a": "Rio de Janeiro",
        "b": "Brasília",
        "c": "São Paulo",
        "d": "Salvador"
      }
    }
  ]
}

###

PUT http://localhost:3333/teacher/exams/2
Content-Type: application/json

{
    "examDate": "31/05/2024",
    "questions": [
    {
      "question": "Quem escreveu 'Dom'?",
      "options": {
        "a": "Miguel de Cervantes",
        "b": "William Shakespeare",
        "c": "Jorge Luis Borges",
        "d": "Fernando Pessoa"
      }
    },
    {
      "question": "Qual é o maior planeta do sistema solar?",
      "options": {
        "a": "Júpiter",
        "b": "Terra",
        "c": "Saturno",
        "d": "Netuno"
      }
    }
  ]
}

###

DELETE http://localhost:3333/teacher/exams/1

###

GET http://localhost:3333/classroom/8/students

###

GET http://localhost:3333/classroom/8/student/2/exam-responses

###

GET http://localhost:3333/student/2/exam/44/response